# Generated by Django 4.2 on 2025-09-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0003_add_waste_level_to_sensorreading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='node',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='waste_level',
            field=models.FloatField(default=0.0, help_text='Waste level from 0.00 to 1.00 (0% to 100% full)'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['node', '-timestamp'], name='bins_sensor_node_id_b4aef3_idx'),
        ),
    ]
