# Generated by Django 4.2 on 2025-09-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0004_alter_sensorreading_options_node_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='auto_update_location',
            field=models.BooleanField(default=False, help_text='Automatically use current GPS location when available'),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='latitude',
            field=models.FloatField(blank=True, help_text="User's latitude coordinate for route calculation", null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='location_name',
            field=models.CharField(blank=True, default='', help_text='Optional location name/address for reference', max_length=255),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='longitude',
            field=models.FloatField(blank=True, help_text="User's longitude coordinate for route calculation", null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
