# Generated by Django 4.2 on 2026-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_add_user_location_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='traffic_density',
            field=models.FloatField(default=0.0),
        ),
    ]
