# Generated by Django 4.2 on 2026-08-16 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bins', '0006_sensorreading_traffic_density'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.BigIntegerField(unique=True)),
                ('event_type', models.CharField(choices=[('reading', 'Sensor reading ingested'), ('plan', 'Route plan generated'), ('service', 'Bin serviced'), ('model', 'Model version activated'), ('fault', 'Sensor fault detected'), ('config', 'Configuration changed'), ('genesis', 'Ledger genesis')], max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(max_length=64)),
                ('entry_hash', models.CharField(max_length=64, unique=True)),
                ('merkle_root', models.CharField(blank=True, default='', help_text='Set on the last entry of each block.', max_length=64)),
                ('signature', models.CharField(blank=True, default='', help_text='HMAC-SHA256 when AUDIT_HMAC_KEY is configured.', max_length=64)),
                ('actor', models.CharField(blank=True, default='system', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('open_minute', models.IntegerField(default=0, help_text='Depot opening, minutes from midnight.')),
                ('close_minute', models.IntegerField(default=1440, help_text='Depot closing, minutes from midnight.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('forward_bundle', 'Forward-looking bundle'), ('legacy_rf', 'Legacy random forest'), ('continual', 'Continual residual corrector')], default='forward_bundle', max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=512)),
                ('artifact_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('search_space', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('training_rows', models.IntegerField(default=0)),
                ('validation_scheme', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(default='cvrptw_savings_ls', max_length=48)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('horizon_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('compute_ms', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('arrival_min', models.FloatField(default=0.0, help_text='Minutes after shift start.')),
                ('departure_min', models.FloatField(default=0.0)),
                ('leg_distance_m', models.FloatField(default=0.0)),
                ('leg_co2_kg', models.FloatField(default=0.0)),
                ('load_after_kg', models.FloatField(default=0.0)),
                ('priority', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['vehicle_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='SensorHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('waste_level', 'Waste level'), ('gas_level', 'Gas level'), ('temperature', 'Temperature'), ('humidity', 'Humidity')], max_length=24)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('suspect', 'Suspect'), ('degraded', 'Degraded'), ('failed', 'Failed')], default='ok', max_length=12)),
                ('trust', models.FloatField(default=1.0, help_text='Channel trust weight in [0,1].')),
                ('drift_estimate', models.FloatField(default=0.0, help_text='Estimated additive bias.')),
                ('stuck_streak', models.IntegerField(default=0)),
                ('missing_streak', models.IntegerField(default=0)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fill_at_collection', models.FloatField(default=0.0)),
                ('load_kg', models.FloatField(default=0.0)),
                ('wait_hours', models.FloatField(default=0.0, help_text='Hours since the previous collection.')),
                ('was_overflowing', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('capacity_kg', models.FloatField(default=6000.0)),
                ('shift_minutes', models.FloatField(default=480.0, help_text='Hard shift duration limit.')),
                ('shift_start_minute', models.IntegerField(default=360, help_text='Shift start, minutes from midnight.')),
                ('avg_speed_kmh', models.FloatField(default=20.0, help_text='Free-flow planning speed.')),
                ('kerb_mass_kg', models.FloatField(default=12000.0, help_text='Empty vehicle mass (payload model).')),
                ('euro_class', models.CharField(choices=[('euro3', 'Euro III'), ('euro4', 'Euro IV'), ('euro5', 'Euro V'), ('euro6', 'Euro VI'), ('ev', 'Battery electric')], default='euro4', max_length=8)),
                ('compaction_ratio', models.FloatField(default=2.5, help_text='Volume reduction achieved on board.')),
                ('accepts_streams', models.JSONField(blank=True, default=list, help_text='Waste streams this vehicle may collect; empty means all.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='collectionroute',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='node',
            name='capacity_liters',
            field=models.FloatField(default=1100.0, help_text='Nominal bin volume in litres (EN 840 1100 L default).'),
        ),
        migrations.AddField(
            model_name='node',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='node',
            name='last_collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='service_minutes',
            field=models.FloatField(default=4.0, help_text='Time a crew needs on site to empty this bin.'),
        ),
        migrations.AddField(
            model_name='node',
            name='waste_density_kg_per_m3',
            field=models.FloatField(default=220.0, help_text='Uncompacted municipal solid waste bulk density.'),
        ),
        migrations.AddField(
            model_name='node',
            name='waste_stream',
            field=models.CharField(choices=[('general', 'General'), ('organic', 'Organic'), ('recyclable', 'Recyclable'), ('hazardous', 'Hazardous')], default='general', max_length=16),
        ),
        migrations.AddField(
            model_name='node',
            name='window_end_min',
            field=models.IntegerField(default=1440, help_text='Latest servicing time, minutes after shift start.'),
        ),
        migrations.AddField(
            model_name='node',
            name='window_start_min',
            field=models.IntegerField(default=0, help_text='Earliest servicing time, minutes after shift start.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(blank=True, default='general', max_length=24),
        ),
        migrations.AddField(
            model_name='notification',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='bins.node'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='battery_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='fault_label',
            field=models.CharField(blank=True, default='', help_text='Ground-truth fault mode when injected (evaluation only).', max_length=32),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='is_synthetic',
            field=models.BooleanField(default=False, help_text='True when produced by the simulator or a fault-injection run.'),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='rssi_dbm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='aging_gamma',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='aging_tau_h',
            field=models.FloatField(default=48.0),
        ),
        migrations.AddField(
            model_name='usersetting',
            name='routing_alpha',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='gas_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='traffic_density',
            field=models.FloatField(default=0.0, help_text='Observed congestion 0.0-1.0.'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='waste_level',
            field=models.FloatField(blank=True, default=0.0, help_text='Fill fraction 0.00-1.00. NULL marks a genuinely missing channel.', null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='auto_update_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='latitude',
            field=models.FloatField(blank=True, help_text="User's latitude for route calculation", null=True),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='longitude',
            field=models.FloatField(blank=True, help_text="User's longitude for route calculation", null=True),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['-timestamp'], name='bins_sensor_timesta_274c84_idx'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='bins.depot'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_events', to='bins.node'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='bins.routeplan'),
        ),
        migrations.AddField(
            model_name='serviceevent',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_events', to='bins.vehicle'),
        ),
        migrations.AddField(
            model_name='sensorhealth',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='bins.node'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bins.node'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bins.routeplan'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bins.vehicle'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='modelversion',
            unique_together={('kind', 'version')},
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['sequence'], name='bins_audite_sequenc_b335b3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditentry',
            index=models.Index(fields=['event_type', '-created_at'], name='bins_audite_event_t_1638ae_idx'),
        ),
        migrations.AddField(
            model_name='collectionroute',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_routes', to='bins.routeplan'),
        ),
        migrations.AddIndex(
            model_name='serviceevent',
            index=models.Index(fields=['node', '-collected_at'], name='bins_servic_node_id_0a3620_idx'),
        ),
        migrations.AddIndex(
            model_name='sensorhealth',
            index=models.Index(fields=['node', 'channel'], name='bins_sensor_node_id_05fc1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sensorhealth',
            unique_together={('node', 'channel')},
        ),
        migrations.AddIndex(
            model_name='routestop',
            index=models.Index(fields=['plan', 'vehicle', 'sequence'], name='bins_routes_plan_id_6ca5e6_idx'),
        ),
    ]
