# Generated by Django 4.2 on 2026-08-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0007_auditentry_depot_modelversion_routeplan_routestop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_volume_m3',
            field=models.FloatField(default=16.0, help_text='Usable body volume in cubic metres. Compaction reduces the volume a load occupies, so this is the limit compaction acts on. Household waste is light and bulky, so volume usually binds before mass. Zero disables the volume constraint.'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity_kg',
            field=models.FloatField(default=6000.0, help_text='Payload mass limit in kg. Mass is conserved: compaction does not reduce it.'),
        ),
    ]
