# Generated by Django 4.2 on 2026-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0008_vehicle_body_volume_m3_alter_vehicle_capacity_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_volume_m3',
            field=models.FloatField(default=16.0, help_text='Usable body volume in cubic metres. Compaction reduces the volume a load occupies, so this is the limit compaction acts on. Whether volume or mass binds first depends on density: they meet at capacity_kg / (volume * compaction), which is 150 kg/m3 at the defaults, so mass binds for the densities configured here. Zero disables the volume constraint.'),
        ),
    ]
